apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: hive-og
spec:
  targetNamespaces:
  - hive
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hive-operator
  namespace: hive
spec:
  channel: ocm-2.1
  installPlanApproval: Automatic
  name: hive-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: hive-operator.v1.0.8
