apiVersion: hive.openshift.io/v1
kind: HiveConfig
metadata:
  name: hive
spec:
  globalPullSecretRef:
    name: global-pull-secret
  managedDomains:
  - aws:
      credentialsSecretRef:
        name: global-aws-creds
    domains:
    - hive.multicloudops.io
